add games: rps and cube
soulfulolya20/SenlaCourse pull request #2
Opened 2022-03-31 14:39 UTC by soulfulolya20

2022-04-06 20:22 UTC, igorpenkin requested changes

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +    var cubeLabel1: UILabel! = {
Зачем здесь " ! " ?

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        let label = UILabel(frame: CGRect(x: 154, y: 250, width: 80, height: 80))
Фрейм должен задаваться строго в методе контроллера viewDidLayoutSubviews() или в самой вью контроллера layoutSubviews()

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        let label = UILabel(frame: CGRect(x: 154, y: 250, width: 80, height: 80))
У остальных лейблов так же

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        view.backgroundColor = .white
Тогда это логичнее перенести в setupView()

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        view?.addSubview(cubeLabel1)
Зачем " ? " ?

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        restartButton.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
Активировать констрейнты лучше внутри NSLayoutConstraint.avtivate([....  ])

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/CubeGameController.swift
> +        switch randomResult {
Лучше закинуть лейблы в стеквью, у стек вью будет проперти arrangedSubviews или просто subview, и из нее брать рандомный элемент как из массива, switch тут совсем не нужен

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/RockPaperScissorsController.swift
> +    var nameOfGame: UILabel! = {
Зачем тут и ниже "!" ?

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/RockPaperScissorsController.swift
> +        paperButton.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
viewDidLayoutSubviews() этот метод вызывается несколько раз во время жизненного цикла контроллера, каждый раз ты в нем сетуешь одни и те же констрейнты что приводит к не нужным лишним просчетам, убери это в отдельный метод и вызови его во viewDidLoad()

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/RockPaperScissorsController.swift
> +        view.backgroundColor = .white
Логичнее перенести в setuoView()

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/RockPaperScissorsController.swift
> +            nameOfGame.topAnchor.constraint(equalTo: view.topAnchor, constant: 190).isActive = true
Почему контсрейнты устанавливаются в разных местах?

2022-04-06 20:22 UTC, igrpnkn commented on firstApp/firstApp/RockPaperScissorsController.swift
> +            ResultLabel.text = "Ньчья, Ваш выбор - Камень, \nпротивник выбрал Камень!"
Зачем алгоритму игры знать что-то о том какой перевод выбирать, подумай как вынести логику сеттинга перевода из функции игры

2022-04-06 20:22 UTC, igorpenkin commented on firstApp/firstApp/RockPaperScissorsController.swift
> +    func rockButtonAction() {
У тебя в трех методах
rockButtonAction()
paperButtonAction()
scissorsButtonAction()

происходит одна и та же логика, подумай как это можно сделать в рамках одного метода без дублирования кода

2022-04-06 20:22 UTC, igorpenkin commented on firstApp/firstApp/RockPaperScissorsController.swift
> +        view.addSubview(ResultLabel)
Зачем каждый раз добавлять его на view?
И в остальных местах по коду аналогично

2022-04-06 20:22 UTC, igorpenkin commented on firstApp/firstApp/RockPaperScissorsController.swift
> +        view.backgroundColor = .white
ЗАчем 100500 раз задавать фоновый цвет?

2022-04-06 20:22 UTC, igorpenkin commented on firstApp/firstApp/SceneDelegate.swift
> +        let mainVC = RockPaperScissorsController()
Настройка контроллеров не должна происходить в SceneDelegate, переноси этот код в TabBarController

2022-04-16 22:01 UTC, merged

2022-04-16 22:35 UTC, soulfulolya20 commented
.